In [1]:
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
import sklearn
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import pickle
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier

In [3]:
df=pd.read_csv("/Users/Tiphani/Desktop/dataset.csv")

In [4]:
df.head()

feeling.nervous panic breathing.rapidly sweating trouble.in.concentration  \
0             yes   yes               yes      yes                      yes   
1              no    no                no       no                       no   
2              no    no                no       no                       no   
3              no    no                no       no                       no   
4              no    no                no       no                       no   

  having.trouble.in.sleeping having.trouble.with.work hopelessness anger  \
0                        yes                       no           no    no   
1                         no                      yes          yes   yes   
2                         no                       no           no    no   
3                         no                       no           no    no   
4                         no                       no           no    no   

  over.react  ... weight.gain material.possessions introvert  \
0         no  ...          no                   no        no   
1        yes  ...          no                   no        no   
2         no  ...         yes                  yes       yes   
3         no  ...          no                   no        no   
4         no  ...          no                   no        no   

  popping.up.stressful.memory having.nightmares avoids.people.or.activities  \
0                          no                no                          no   
1                          no                no                          no   
2                          no                no                          no   
3                         yes               yes                         yes   
4                          no                no                          no   

  feeling.negative trouble.concentrating blaming.yourself    Disorder  
0               no                    no               no     Anxiety  
1               no                    no               no  Depression  
2               no                    no               no  Loneliness  
3              yes                   yes              yes      Stress  
4               no                    no               no      Normal  

[5 rows x 25 columns]

In [5]:
df.isnull().values.any()

False

In [6]:
df['feeling.nervous']=df['feeling.nervous'].apply(lambda x:1 if x =='yes' else 0)
df['panic']=df['panic'].apply(lambda x:1 if x=='yes' else 0)
df['breathing.rapidly']=df['breathing.rapidly'].apply(lambda x:1 if x=='yes' else 0)
df['sweating']=df['sweating'].apply(lambda x:1 if x=='yes' else 0)
df['trouble.in.concentration']=df['trouble.in.concentration'].apply(lambda x:1 if x=='yes' else 0)
df['having.trouble.in.sleeping']=df['having.trouble.in.sleeping'].apply(lambda x:1 if x =='yes' else 0)
df['having.trouble.with.work']=df['having.trouble.with.work'].apply(lambda x:1 if x =='yes' else 0)
df['hopelessness']=df['hopelessness'].apply(lambda x:1 if x =='yes' else 0)
df['anger']=df['anger'].apply(lambda x:1 if x =='yes' else 0)
df['change.in.eating']=df['change.in.eating'].apply(lambda x:1 if x =='yes' else 0)
df['suicidal.thought']=df['suicidal.thought'].apply(lambda x:1 if x =='yes' else 0)
df['feeling.tired']=df['feeling.tired'].apply(lambda x:1 if x =='yes' else 0)
df['close.friend']=df['close.friend'].apply(lambda x:1 if x =='yes' else 0)
df['popping.up.stressful.memory']=df['popping.up.stressful.memory'].apply(lambda x:1 if x =='yes' else 0)
df['having.nightmares']=df['having.nightmares'].apply(lambda x:1 if x =='yes' else 0)
df['avoids.people.or.activities']=df['avoids.people.or.activities'].apply(lambda x:1 if x =='yes' else 0)
df['feeling.negative']=df['feeling.negative'].apply(lambda x:1 if x =='yes' else 0)
df['trouble.concentrating']=df['trouble.concentrating'].apply(lambda x:1 if x =='yes' else 0)
df['blaming.yourself']=df['blaming.yourself'].apply(lambda x:1 if x =='yes' else 0)

X=df[['feeling.nervous', 'panic', 'breathing.rapidly', 'sweating', 'trouble.in.concentration', 'having.trouble.in.sleeping','having.trouble.with.work','hopelessness','anger','change.in.eating','suicidal.thought','feeling.tired','close.friend','popping.up.stressful.memory','having.nightmares','avoids.people.or.activities','feeling.negative','trouble.concentrating', 'blaming.yourself']].values

In [7]:
X

array([[1, 1, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [8]:
df['Disorder']=df['Disorder'].apply(lambda x:1 if x == 'Anxiety' else 2 if x=='Depression' else 3 if x == 'Loneliness' else 4 if x == 'Stress' else 5)
y = df['Disorder'].values

In [9]:
y

array([1, 2, 3, ..., 3, 4, 5], dtype=int64)

In [10]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [11]:
model = RandomForestClassifier(n_estimators=20)
model.fit(X_train,y_train)

RandomForestClassifier(n_estimators=20)

In [12]:
model.score(X_test,y_test)

1.0

In [13]:
model.predict(X_test)

array([3, 1, 5, ..., 3, 4, 4], dtype=int64)

In [14]:
pickle.dump(model, open('disorder.pkl', 'wb'))

In [15]:
disorder = pickle.load(open('disorder.pkl', 'rb'))

In [16]:
disorder.predict(X_test)

array([3, 1, 5, ..., 3, 4, 4], dtype=int64)